# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: "Notebook Pipeline (Ubuntu)"

on:
  pull_request:
    branches: 
      - main
      - NG20

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Install pdflatex
      run: |
        sudo apt-get update
        sudo apt-get install texlive-latex-base cm-super-minimal pdftk latex2html
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v3
      with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
    - name: Conda info
      shell: bash -el {0}
      run: conda info
    - name: Install Dependencies & Main Code
      shell: bash -el {0}
      run: |
        mamba install -c conda-forge python=${{ matrix.python-version }} pytest cython=0.29.36 tempo2 enterprise-pulsar enterprise_extensions scikit-sparse
        pip install -e .
    - name: Test with Standard Pulsar
      shell: bash -el {0}
      run: |
        export PULSAR_NAME='J0605+3757'
        export JUPYTER_PLATFORM_DIRS=1 && jupyter --paths
        tree tests
        pytest tests/test_run_notebook.py -n auto -k $PULSAR_NAME
        mv tmp-* nb_outputs
    - name: Archive Notebook Output Files
      uses: actions/upload-artifact@v3
      with:
        name: TestNB-OutputFiles
        path: |
          nb_outputs
        
